### ISSUE TITLE
"latest release" not found. unable to download Remnant Save Guardian.

### ISSUE THREAD

**Issue by dgvall** [Razzmatazzz/RemnantSaveGuardian#281]
"latest release" not found. unable to download Remnant Save Guardian.

**Comment by dgvall** [comment]
referring to the "latest release" hyperlink that sends to this URL https://github.com/Razzmatazzz/RemnantSaveGuardian/releases/download/1.3.3/RemnantSaveGuardian.zip

**Comment by suspended7th** [comment]
I believe I have found the problem and the solution for this whenever someone with perms to edit things has a chance.

The problem is that the file in that release is named RemnantSaveGuardian_1.3.3.0.zip and the link (and I am assuming the updater in the app itself) point to RemnantSaveGuardian.zip.   If the name of the file is changed back to not include the release number it should function properly again.

**Comment by Q-Sharp** [comment]
I fixed the problem in the autoupdater. But sadly @Razzmatazzz changed the pattern of the newest release name and now its broken again. 😒

**Comment by suspended7th** [comment]
I think this is going to be an issue every time a new update comes out.  The auto-updater is already broken again because a new version came out.  I am not super familiar with releasing code from github, but unless a wildcard can be added to the download link it is going to need to be manually updated for each release.  I am not going to stick my nose into it too deep, I can just come here and manually download updates, but it may be worth @Razzmatazzz considering returning to the old naming convention for the zip file but changing the executable name to include the version.

**Comment by Razzmatazzz** [comment]
The underlying problem is it shouldn't be using a hard-coded URL to download the new version. I just pushed out a fix.
